version: '2'
services:
  postgres:
    container_name: clair_postgres
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password

  clair:
    container_name: clair_clair
    image: quay.io/coreos/clair-git:latest
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "6060-6061:6060-6061"
    links:
      - postgres
    volumes:
      - /tmp:/tmp
      - ./clair_config:/config
    command: [-config, /config/config.yaml]
#    environment:
#      - SOCKS_PROXY="http://proxy-us.intel.com:1080"
#      - HTTP_PROXY=http://proxy-chain.intel.com:911
#      - HTTPS_PROXY=http://proxy-chain.intel.com:912

